//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTema2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceTema2Soap")]
    public interface WebServiceTema2Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientTema2.ServiceReference1.HelloWorldResponse HelloWorld(ClientTema2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTema2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ClientTema2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToBiblioteca", ReplyAction="*")]
        ClientTema2.ServiceReference1.AddToBibliotecaResponse AddToBiblioteca(ClientTema2.ServiceReference1.AddToBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToBiblioteca", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTema2.ServiceReference1.AddToBibliotecaResponse> AddToBibliotecaAsync(ClientTema2.ServiceReference1.AddToBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFromBiblioteca", ReplyAction="*")]
        void DeleteFromBiblioteca(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFromBiblioteca", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteFromBibliotecaAsync(int id);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyBibliotecaData", ReplyAction="*")]
        ClientTema2.ServiceReference1.ModifyBibliotecaDataResponse ModifyBibliotecaData(ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyBibliotecaData", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTema2.ServiceReference1.ModifyBibliotecaDataResponse> ModifyBibliotecaDataAsync(ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientTema2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientTema2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientTema2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientTema2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToBibliotecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToBiblioteca", Namespace="http://tempuri.org/", Order=0)]
        public ClientTema2.ServiceReference1.AddToBibliotecaRequestBody Body;
        
        public AddToBibliotecaRequest() {
        }
        
        public AddToBibliotecaRequest(ClientTema2.ServiceReference1.AddToBibliotecaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddToBibliotecaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string editura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int yearPublished;
        
        public AddToBibliotecaRequestBody() {
        }
        
        public AddToBibliotecaRequestBody(int id, string title, string author, string editura, int yearPublished) {
            this.id = id;
            this.title = title;
            this.author = author;
            this.editura = editura;
            this.yearPublished = yearPublished;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToBibliotecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToBibliotecaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientTema2.ServiceReference1.AddToBibliotecaResponseBody Body;
        
        public AddToBibliotecaResponse() {
        }
        
        public AddToBibliotecaResponse(ClientTema2.ServiceReference1.AddToBibliotecaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddToBibliotecaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddToBibliotecaResult;
        
        public AddToBibliotecaResponseBody() {
        }
        
        public AddToBibliotecaResponseBody(int AddToBibliotecaResult) {
            this.AddToBibliotecaResult = AddToBibliotecaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyBibliotecaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyBibliotecaData", Namespace="http://tempuri.org/", Order=0)]
        public ClientTema2.ServiceReference1.ModifyBibliotecaDataRequestBody Body;
        
        public ModifyBibliotecaDataRequest() {
        }
        
        public ModifyBibliotecaDataRequest(ClientTema2.ServiceReference1.ModifyBibliotecaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyBibliotecaDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string editura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int year;
        
        public ModifyBibliotecaDataRequestBody() {
        }
        
        public ModifyBibliotecaDataRequestBody(int id, string title, string author, string editura, int year) {
            this.id = id;
            this.title = title;
            this.author = author;
            this.editura = editura;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyBibliotecaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyBibliotecaDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientTema2.ServiceReference1.ModifyBibliotecaDataResponseBody Body;
        
        public ModifyBibliotecaDataResponse() {
        }
        
        public ModifyBibliotecaDataResponse(ClientTema2.ServiceReference1.ModifyBibliotecaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyBibliotecaDataResponseBody {
        
        public ModifyBibliotecaDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTema2SoapChannel : ClientTema2.ServiceReference1.WebServiceTema2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTema2SoapClient : System.ServiceModel.ClientBase<ClientTema2.ServiceReference1.WebServiceTema2Soap>, ClientTema2.ServiceReference1.WebServiceTema2Soap {
        
        public WebServiceTema2SoapClient() {
        }
        
        public WebServiceTema2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTema2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTema2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTema2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTema2.ServiceReference1.HelloWorldResponse ClientTema2.ServiceReference1.WebServiceTema2Soap.HelloWorld(ClientTema2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientTema2.ServiceReference1.HelloWorldRequest inValue = new ClientTema2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClientTema2.ServiceReference1.HelloWorldRequestBody();
            ClientTema2.ServiceReference1.HelloWorldResponse retVal = ((ClientTema2.ServiceReference1.WebServiceTema2Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTema2.ServiceReference1.HelloWorldResponse> ClientTema2.ServiceReference1.WebServiceTema2Soap.HelloWorldAsync(ClientTema2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTema2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ClientTema2.ServiceReference1.HelloWorldRequest inValue = new ClientTema2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClientTema2.ServiceReference1.HelloWorldRequestBody();
            return ((ClientTema2.ServiceReference1.WebServiceTema2Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTema2.ServiceReference1.AddToBibliotecaResponse ClientTema2.ServiceReference1.WebServiceTema2Soap.AddToBiblioteca(ClientTema2.ServiceReference1.AddToBibliotecaRequest request) {
            return base.Channel.AddToBiblioteca(request);
        }
        
        public int AddToBiblioteca(int id, string title, string author, string editura, int yearPublished) {
            ClientTema2.ServiceReference1.AddToBibliotecaRequest inValue = new ClientTema2.ServiceReference1.AddToBibliotecaRequest();
            inValue.Body = new ClientTema2.ServiceReference1.AddToBibliotecaRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.editura = editura;
            inValue.Body.yearPublished = yearPublished;
            ClientTema2.ServiceReference1.AddToBibliotecaResponse retVal = ((ClientTema2.ServiceReference1.WebServiceTema2Soap)(this)).AddToBiblioteca(inValue);
            return retVal.Body.AddToBibliotecaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTema2.ServiceReference1.AddToBibliotecaResponse> ClientTema2.ServiceReference1.WebServiceTema2Soap.AddToBibliotecaAsync(ClientTema2.ServiceReference1.AddToBibliotecaRequest request) {
            return base.Channel.AddToBibliotecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTema2.ServiceReference1.AddToBibliotecaResponse> AddToBibliotecaAsync(int id, string title, string author, string editura, int yearPublished) {
            ClientTema2.ServiceReference1.AddToBibliotecaRequest inValue = new ClientTema2.ServiceReference1.AddToBibliotecaRequest();
            inValue.Body = new ClientTema2.ServiceReference1.AddToBibliotecaRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.editura = editura;
            inValue.Body.yearPublished = yearPublished;
            return ((ClientTema2.ServiceReference1.WebServiceTema2Soap)(this)).AddToBibliotecaAsync(inValue);
        }
        
        public void DeleteFromBiblioteca(int id) {
            base.Channel.DeleteFromBiblioteca(id);
        }
        
        public System.Threading.Tasks.Task DeleteFromBibliotecaAsync(int id) {
            return base.Channel.DeleteFromBibliotecaAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTema2.ServiceReference1.ModifyBibliotecaDataResponse ClientTema2.ServiceReference1.WebServiceTema2Soap.ModifyBibliotecaData(ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest request) {
            return base.Channel.ModifyBibliotecaData(request);
        }
        
        public void ModifyBibliotecaData(int id, string title, string author, string editura, int year) {
            ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest inValue = new ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest();
            inValue.Body = new ClientTema2.ServiceReference1.ModifyBibliotecaDataRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.editura = editura;
            inValue.Body.year = year;
            ClientTema2.ServiceReference1.ModifyBibliotecaDataResponse retVal = ((ClientTema2.ServiceReference1.WebServiceTema2Soap)(this)).ModifyBibliotecaData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTema2.ServiceReference1.ModifyBibliotecaDataResponse> ClientTema2.ServiceReference1.WebServiceTema2Soap.ModifyBibliotecaDataAsync(ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest request) {
            return base.Channel.ModifyBibliotecaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTema2.ServiceReference1.ModifyBibliotecaDataResponse> ModifyBibliotecaDataAsync(int id, string title, string author, string editura, int year) {
            ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest inValue = new ClientTema2.ServiceReference1.ModifyBibliotecaDataRequest();
            inValue.Body = new ClientTema2.ServiceReference1.ModifyBibliotecaDataRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.editura = editura;
            inValue.Body.year = year;
            return ((ClientTema2.ServiceReference1.WebServiceTema2Soap)(this)).ModifyBibliotecaDataAsync(inValue);
        }
    }
}
